name: Relaunch Workflow

on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed

jobs:
  redeploy:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          echo "${{ secrets.GH_PAT }}" | gh auth login --with-token
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Check for "Shutting down..." in Main Workflow logs
        id: check_logs
        run: |
          RUN_ID=$(gh run list --workflow="Main Workflow" --json databaseId --jq '.[0].databaseId')
          if [ -z "$RUN_ID" ]; then
            echo "No recent run found. Exiting check."
            echo "shutdown_found=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          LOG_OUTPUT=$(gh run view "$RUN_ID" --log || echo "LOG_FETCH_ERROR")
          if [ "$LOG_OUTPUT" == "LOG_FETCH_ERROR" ]; then
            echo "Failed to fetch logs."
            echo "shutdown_found=false" >> $GITHUB_OUTPUT
            exit 0
          fi
            
          if echo "$LOG_OUTPUT" | grep -q "Shutting down..."; then
            echo "shutdown_found=true" >> $GITHUB_OUTPUT
          else
            echo "shutdown_found=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          
      - name: Trigger Main Workflow
        if: env.shutdown_found == 'false'
        run: |
          gh workflow run "Main Workflow"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
